databases:
  - name: mysite
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn project.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.ieorgodyevftbbftquew:W3W5bEX1yze4zoYb@aws-0-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: RENDER_EXTERNAL_HOSTNAME
        value: mysite.onrender.com
