# Generated by Django 4.2.1 on 2024-01-27 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField()),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_charts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
