# Generated by Django 4.2.1 on 2024-01-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='departmentNames',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chart',
            name='personCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
