# Generated by Django 4.2.1 on 2024-01-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chart_departmentnames_chart_personcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='departmentNames',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
