# Generated by Django 4.2.1 on 2024-02-15 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_alter_chart_departmentnames'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_grant_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_time', models.DateTimeField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='myapp.chart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
