# Generated by Django 4.2.1 on 2024-02-15 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chartaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartaccess',
            name='access_grant_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 20, 3, 44, 794216, tzinfo=datetime.timezone.utc)),
        ),
    ]
