# Generated by Django 4.2.1 on 2024-02-15 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_chartaccess_access_grant_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartaccess',
            name='access_grant_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
