# Generated by Django 5.0.3 on 2024-04-11 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='user_uploaded/user_images/'),
        ),
        migrations.CreateModel(
            name='ClientLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, max_length=2000)),
                ('org_website', models.CharField(blank=True, max_length=2000)),
                ('designations', models.CharField(blank=True, max_length=2000)),
                ('dept_names', models.CharField(blank=True, max_length=2000)),
                ('industry_types', models.CharField(blank=True, max_length=2000)),
                ('locations', models.CharField(blank=True, max_length=2000)),
                ('total_charts', models.IntegerField(blank=True)),
                ('required_authorities', models.IntegerField(blank=True)),
                ('extra_insighhts', models.CharField(blank=True, max_length=2000)),
                ('include_contacts', models.BooleanField(default=False)),
                ('sow_status', models.CharField(blank=True, default='Pending', max_length=100)),
                ('payment_status', models.CharField(blank=True, default='Pending', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('emp_range', models.CharField(blank=True, max_length=100)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('amount_in_currency', models.DecimalField(decimal_places=2, max_digits=20)),
                ('amount_in_inr', models.DecimalField(decimal_places=2, max_digits=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
