# Generated by Django 5.1.1 on 2025-05-26 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_chart_country_chart_employee_range_chart_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='access_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
