# Generated by Django 5.1.1 on 2025-05-26 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_userprofile_access_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='access_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
