# Generated by Django 5.0.2 on 2025-06-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_order_orderitem'),
    ]

    operations = [
    ]
