# Generated by Django 5.0.2 on 2025-06-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='InsideOrgs - Sphurti WebApp Pvt. Ltd.', max_length=200)),
                ('address_line1', models.CharField(default='House Number A2/6, Back Side of Mhada Colony, Raj Swapnpurti Elite Row,', max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(default='Chhatrapati Sambhajinagar', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(default='431002', max_length=20)),
                ('phone', models.CharField(default='+91 86683 35926', max_length=20)),
                ('email', models.EmailField(default='info@sphurti.net', max_length=254)),
                ('website', models.URLField(default='https://insideorgs.sphurti.net')),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_ifsc_code', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
    ]
