# Generated by Django 5.0.2 on 2025-06-15 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_userprofile_billing_address_line1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_address_line1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_address_line2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_gst_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_pan_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_postal_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_state',
        ),
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Information',
                'verbose_name_plural': 'Customer Information',
            },
        ),
    ]
