# Generated by Django 5.0.2 on 2025-06-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_order_base_amount_order_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_gst',
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Tax ID/VAT/GST number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
