# Generated by Django 5.0.2 on 2025-06-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cgst_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sgst_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='order',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='5.5% processing fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
