# Generated by Django 5.0.2 on 2025-06-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_order_status_refundlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundlog',
            name='reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
