# Generated by Django 5.0.2 on 2025-06-20 01:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_refundlog_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
