# Generated by Django 5.0.2 on 2025-06-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_chart_uuid_alter_chart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_link', models.URLField(default='https://dash.sphurti.net/charts/Sphurti-WebApp-Solutions%20(Demo)%20-%20Org.html', help_text='URL for the free sample chart link', max_length=500)),
                ('sample_title', models.CharField(default='Free Sample', help_text='Title for the sample link', max_length=100)),
                ('sample_description', models.CharField(default='Preview our demo chart', help_text='Description for the sample link', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketplace Settings',
                'verbose_name_plural': 'Marketplace Settings',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='img/user/'),
        ),
    ]
