# Generated by Django 4.2.23 on 2025-07-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_samplerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='has_preview_version',
            field=models.BooleanField(default=False, help_text='Check if this chart has a separate preview version for marketplace'),
        ),
        migrations.AddField(
            model_name='chart',
            name='preview_chart_title',
            field=models.CharField(blank=True, help_text='Title for the preview version (will be used for preview file name)', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='preview_notes',
            field=models.TextField(blank=True, help_text='Internal notes about the preview version', null=True),
        ),
    ]
